package com.bmw1975487.aione;
import android.app.Activity; import android.content.Intent; import android.graphics.Color; import android.net.VpnService; import android.os.*; import android.view.Gravity; import android.widget.*; import com.bmw1975487.aione.core.*; import com.bmw1975487.aione.diag.AppLog; import com.bmw1975487.aione.vpn.AiVpnService;
public final class MainActivity extends Activity {
 private static final int RQ=1001; private final Handler h=new Handler(Looper.getMainLooper()); private TextView st,dt; private Button b;
 private final Runnable poll=new Runnable(){public void run(){render();h.postDelayed(this,500);}};
 protected void onCreate(Bundle x){super.onCreate(x); AppLog.i(this,"ACTIVITY_CREATE","sdk="+Build.VERSION.SDK_INT); setContentView(ui()); render(); h.post(poll);}
 private LinearLayout ui(){LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.VERTICAL);r.setGravity(Gravity.CENTER);int p=dp(24);r.setPadding(p,p,p,p);r.setBackgroundColor(Color.WHITE);TextView t=new TextView(this);t.setText("AI ACCESS ONE");t.setTextSize(28);t.setGravity(Gravity.CENTER);r.addView(t,new LinearLayout.LayoutParams(-1,-2));st=new TextView(this);st.setTextSize(22);st.setGravity(Gravity.CENTER);r.addView(st,new LinearLayout.LayoutParams(-1,-2));dt=new TextView(this);dt.setGravity(Gravity.CENTER);r.addView(dt,new LinearLayout.LayoutParams(-1,-2));b=new Button(this);b.setAllCaps(false);b.setOnClickListener(v->act());r.addView(b,new LinearLayout.LayoutParams(-1,dp(64)));return r;}
 private void act(){String s=StateStore.state(this);if(AppConstants.STATE_READY.equals(s)||AppConstants.STATE_SERVICE_STARTED.equals(s)||AppConstants.STATE_PREPARING.equals(s)){stopService(new Intent(this,AiVpnService.class));StateStore.set(this,AppConstants.STATE_OFF,"Остановлено");return;}StateStore.set(this,AppConstants.STATE_PREPARING,"Запрос VPN-разрешения");Intent i=VpnService.prepare(this);if(i!=null)startActivityForResult(i,RQ);else startVpn();}
 protected void onActivityResult(int q,int r,Intent d){super.onActivityResult(q,r,d);if(q==RQ){if(r==RESULT_OK)startVpn();else StateStore.set(this,AppConstants.STATE_ERROR,"VPN-разрешение не выдано");}}
 private void startVpn(){Intent i=new Intent(this,AiVpnService.class);try{if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);StateStore.set(this,AppConstants.STATE_SERVICE_STARTED,"Сервис запущен");}catch(Throwable t){StateStore.set(this,AppConstants.STATE_ERROR,t.getClass().getSimpleName());}}
 private void render(){String s=StateStore.state(this);dt.setText(StateStore.detail(this));if(AppConstants.STATE_READY.equals(s)){st.setText("ВКЛЮЧЕНО");b.setText("ВЫКЛ");}else if(AppConstants.STATE_ERROR.equals(s)){st.setText("ОШИБКА");b.setText("ПОВТОРИТЬ");}else if(AppConstants.STATE_PREPARING.equals(s)||AppConstants.STATE_SERVICE_STARTED.equals(s)){st.setText("ПОДКЛЮЧЕНИЕ…");b.setText("ВЫКЛ");}else{st.setText("ВЫКЛ");b.setText("ВКЛЮЧИТЬ");}}
 private int dp(int v){return Math.round(v*getResources().getDisplayMetrics().density);} protected void onDestroy(){h.removeCallbacks(poll);super.onDestroy();}
}
